image: $CI_REGISTRY/just1ce/poster/docker

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - cp -u .env.example .env
    - docker-compose -f compose.base.yml -f compose.dev.yml up -d
    - docker exec poster bash ./deploy.sh
    - docker-compose -f compose.base.yml -f compose.dev.yml down
  cache:
    paths:
      - vendor/

deploy:
  stage: deploy
  script:
    - cp -u .env.example .env
    - docker-compose -f compose.base.yml -f compose.prod.yml build
    - docker-compose -f compose.base.yml -f compose.prod.yml push