image: $CI_REGISTRY/just1ce/poster/docker

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

cache:
    paths:
      - vendor/

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - cp -u .env.example .env
    - docker-compose -f compose.base.yml -f compose.dev.yml up --build --quiet-pull
    - docker exec poster ./deploy.sh

deploy:
  stage: deploy
  script:
    - cp -u .env.example .env
    - docker-compose -f compose.base.yml -f compose.prod.yml build --quiet-pull
    - docker-compose -f compose.base.yml -f compose.prod.yml push