image: $CI_REGISTRY/just1ce/poster/docker

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" >> sshkey
  - chmod 400 sshkey
  - ssh-add sshkey
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  
build:
  stage: build
  script:
    - cp -u .env.example .env
    - docker-compose -f compose.base.yml -f compose.dev.yml pull
    - docker-compose -f compose.base.yml -f compose.dev.yml up -d --build
    - docker exec poster bash ./deploy.sh
    - docker-compose -f compose.base.yml -f compose.dev.yml down
    - docker-compose -f compose.base.yml -f compose.dev.yml push
  cache:
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/
    when: on_success
    expire_in: 5 mins
  only:
    - master
    - docker-test

deploy:
  stage: deploy
  script:
    - docker-compose -f compose.base.yml -f compose.prod.yml build
    - docker-compose -f compose.base.yml -f compose.prod.yml push
    - scp compose.base.yml just1ce@185.249.255.224:~/www
    - scp compose.prod.yml just1ce@185.249.255.224:~/www
    - ssh just1ce@185.249.255.224 "cd ~/www/ &&
      ENV_FILE="./.env" docker-compose -f compose.base.yml -f compose.prod.yml pull &&
      ENV_FILE="./.env" docker-compose -f compose.base.yml -f compose.prod.yml up"
  when: manual
  only:
    - master
    - docker-test