version: "3"
services:
  web:
    image: registry.gitlab.com/just1ce/poster/nginx:prod
    build:
      dockerfile: ./docker-services/nginx/Dockerfile.prod
    restart: always
    volumes:
      - ${ENV_FILE}:./.env
  app:
    image: registry.gitlab.com/just1ce/poster/php-app:prod
    build:
      dockerfile: ./docker-services/php-base/Dockerfile.prod
    restart: always
  php-cron:
    image: registry.gitlab.com/just1ce/poster/php-cron:prod
    build:
      dockerfile: ./docker-services/php-cron/Dockerfile.prod
     volumes:
      - ${ENV_FILE}:./.env
  phpmyadmin:
    ports:
      - 8996:80
  mysql:
    restart: always