version: "3.2"
services:
  web:
    networks:
      - custom-n
    image: registry.gitlab.com/just1ce/poster/nginx:prod
    build:
      dockerfile: ./docker-services/nginx/Dockerfile.prod
      cache_from:
        - registry.gitlab.com/just1ce/poster/nginx:prod
    restart: always
  app:
    networks:
      - custom-n
    image: registry.gitlab.com/just1ce/poster/php-app:prod
    build:
      dockerfile: ./docker-services/php-base/Dockerfile.prod
      cache_from:
        - registry.gitlab.com/just1ce/poster/php-app:prod
    restart: always
    volumes:
      - ./.env:/var/www/.env
  php-cron:
    networks:
      - custom-n
    image: registry.gitlab.com/just1ce/poster/php-cron:prod
    build:
      dockerfile: ./docker-services/php-cron/Dockerfile.prod
      cache_from:
        - registry.gitlab.com/just1ce/poster/php-cron:prod
    restart: always
    volumes:
      - ./.env:/var/www/.env
  phpmyadmin:
    networks:
      - custom-n
    ports:
      - 8996:80
  mysql:
    networks:
      - custom-n
    restart: always
    
networks:
  custom-n:
    driver: bridge