version: "3"
services:
  web:
    image: just1ce/nginx:prod
    build:
      dockerfile: ./docker-services/nginx/Dockerfile.prod
    restart: always
  app:
    image: just1ce/php-app:prod
    build:
      dockerfile: ./docker-services/php-base/Dockerfile.prod
    restart: always
  php-cron:
    image: just1ce/php-cron:prod
    build:
      dockerfile: ./docker-services/php-cron/Dockerfile.prod
  phpmyadmin:
    ports:
      - 8996:80
  mysql:
    restart: always