version: "3"
services:
  app:
    container_name: poster
    restart: on-failure
    image: just1ce/php-app:dev
    build:
      context: ./
      dockerfile: ./docker-services/php-base/Dockerfile
    depends_on:
      - mysql
  php-cron:
    container_name: php-cron
    restart: on-failure
    image: just1ce/php-cron:dev
    build:
      context: ./
      dockerfile: ./docker-services/php-cron/Dockerfile
    depends_on:
      - mysql
  web:
    container_name: nginx
    image: just1ce/nginx:dev
    build:
      context: ./
      dockerfile: ./docker-services/nginx/Dockerfile
    volumes:
      - /dev/null:/var/log/nginx/access.log
    ports:
      - 80:80
    depends_on:
      - app
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql:cached
  phpmyadmin: 
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_USER=${DB_USERNAME}
      - PMA_HOST=mysql
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
volumes:
  mysql-data:
