version: "3.2"
services:
  app:
    volumes:
      - ./:/var/www:cached
  php-cron:
    volumes:
      - ./:/var/www:cached
  web:
    volumes:
      - ./:/var/www:cached
  phpmyadmin: 
    ports:
      - 81:80