version: "2.2"
services:
  app:
    image: registry.gitlab.com/just1ce/poster/php-app:dev
    build:
      dockerfile: ./docker-services/php-app/Dockerfile.dev
      cache_from:
        - registry.gitlab.com/just1ce/poster/php-app:dev
    volumes:
      - ./:/var/www:cached
  php-cron:
    image: registry.gitlab.com/just1ce/poster/php-cron:dev
    build:
      cache_from:
        - registry.gitlab.com/just1ce/poster/php-cron:dev
    volumes:
      - ./:/var/www:cached
  web:
    image: registry.gitlab.com/just1ce/poster/nginx:dev
    build:
      cache_from:
        - registry.gitlab.com/just1ce/poster/nginx:dev
    volumes:
      - ./public:/var/www/public:cached
  phpmyadmin:
    environment:
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 81:80
  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
