version: "3"
services:
  app:
    container_name: poster
    user: $USER
    restart: on-failure
    build:
      args:
        user: $USER
      context: ./docker-app
      dockerfile: ./Dockerfile
    volumes: ["./:/var/www:cached"]
    ports: ["80:8080"]
    environment:
      - VHOST_DOMAIN="poster.vdev"
    command: 
      - ./deploy.sh
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes: ["./database/data:/var/lib/mysql:cached"]
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_USER=${DB_USERNAME}
      - PMA_HOST=mysql
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 8081:80
    depends_on:
      - mysql
    