version: "2"
services:
  app:
    build:
      context: ./docker-app
      dockerfile: ./Dockerfile
    volumes: ["./:/var/www"]
    ports: ["80:8080"]
    links: 
      - mysql:db
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.6"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes: ["./database/data:/var/lib/mysql"]
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_USER=root
      - PMA_HOST=mysql
      - PMA_PASSWORD=root
    ports:
      - 8081:80
    links: 
      - mysql:mysql
    depends_on:
      - mysql