version: "3"
services:
  app:
    container_name: poster
    restart: on-failure
    image: just1ce/app-php-base:latest
    volumes:
      - ./:/var/www:cached
    depends_on:
      - mysql
  php-cron:
    container_name: php-cron
    restart: on-failure
    build:
      context: ./docker-services/php-cron
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www:cached
    depends_on:
      - mysql
  web:
    container_name: nginx
    build:
      context: ./docker-services/nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes: 
      - ./:/var/www:cached
      - ./logs:/var/log/nginx:cached
    depends_on:
      - app
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql:cached
  phpmyadmin: 
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_USER=${DB_USERNAME}
      - PMA_HOST=mysql
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 81:80
    depends_on:
      - mysql
volumes:
  mysql-data:
